[package]
name = "script_llm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
tracing = "0.1.37"
openai-api-rs = "5.2.3"
tokio = { version = "1.39.3", features = [
    "macros",
    "process",
    "rt-multi-thread",
] }
serde_json = "1.0"
